### ISSUE TITLE
Illegal access_bits value in example playbook

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [linuxhq/ansible-role-rssh#1]
I ran your example playbook and got this error:

```
May 14 22:32:06  rssh[961]: setting umask to 022
May 14 22:32:06  rssh[961]: line 12: configuring user backup
May 14 22:32:06  rssh[961]: syntax error parsing access bits, line 12
May 14 22:32:06  rssh[961]: there were errors processing configuration file!
May 14 22:32:06  rssh[961]: user backup attempted to execute forbidden commands   
```

The problem is that according to [the docs](https://linux.die.net/man/5/rssh.conf), access_bits is 

> Five binary digits, which indicate whether the user is allowed to use rsync, rdist, cvs, sftp, and scp, in that order. One means the command is allowed, zero means it is not.

Counting, in your example, you have 6 digits! Indeed, removing one solve the problem.  I'll fork, branch and submit a PR.

**Comment by tkimball83** [comment]
Interesting, I must have taken those example bits from a bad doc somewhere, for example...

http://manpages.ubuntu.com/manpages/cosmic/man5/rssh.conf.5.html

That documentation states you need 6 digits.

Thanks for the fix, much appreciated!

**Comment by Ths2-9Y-LqJt6** [comment]
Yup yup - the very least I can do to repay the 1/2 day of work I saved by finding this ansible role. Cheers!
