### ISSUE TITLE
control of 'rsshusers' group is missing 

### ISSUE THREAD

**Issue by karolisc** [linuxhq/ansible-role-rssh#4]
`rsshusers` group is hardcoded in the role:
https://github.com/linuxhq/ansible-role-rssh/blob/master/tasks/main.yml#L53

but the role does not check if the group exists nor creates it

**Comment by karolisc** [comment]
https://github.com/linuxhq/ansible-role-rssh/pull/5

**Comment by tkimball83** [comment]
This was likely overlooked as the RPM package should create the group automatically.  This may not be the case for other distributions.

Changes have been merged.  Going to close out this issue.  Thanks!

**Comment by tkimball83** [comment]
https://github.com/linuxhq/ansible-role-rssh/releases/tag/v0.0.5
